package com.example.myweatherapp.domain.model

enum class WeatherForecast {
    CLEAR_SKY,
    MAINLY_CLEAR,

    PARTLY_CLOUDY,
    OVERCAST,
    WINDY,

    DRIZZLE_LIGHT,
    DRIZZLE_MODERATE,
    DRIZZLE_HIGH,

    FREEZING_DRIZZLE_LIGHT,
    FREEZING_DRIZZLE_HIGH,

    RAIN_LIGHT,
    RAIN_MODERATE,
    RAIN_HEAVY,

    FREEZING_RAIN_LIGHT,
    FREEZING_RAIN_HIGH,

    SNOW_MODERATE,
    SNOW_LIGHT,
    SNOW_HEAVY,
    SNOW_GRAINS,

    RAIN_SHOWER_LIGHT,
    RAIN_SHOWER_MODERATE,
    RAIN_SHOWER_HEAVY,

    SNOW_SHOWER_LIGHT,
    SNOW_SHOWER_HEAVY,

    THUNDER_STORM,
    THUNDER_STORM_HAIL_LIGHT,
    THUNDER_STORM_HAIL_HEAVY,

    FOG,
    DEPOSITING_RIME_FOG,

    UNKNOWN_WEATHER_FORECAST
}